### ISSUE TITLE
Bug: comment face is overriden by other faces

### ISSUE THREAD

**Issue by gcentauri** [flexibeast/picolisp-mode#10]
I figured out how to reproduce the comment bug.  It seems like it works fine unless there is another face present on the same line. For example:

![image](https://user-images.githubusercontent.com/760104/62347078-13c56400-b4be-11e9-96bf-b8fa27a42477.png)

I opened this file while investigating, and noticed that the one line of comments is commented out.  I also saw it work on a line like:

`(my-function)`

To reproduce:

  - start a blank line with a comment, should be correct face
  - type anything that would be highlighted in another face, such as `*Foo`

Observed behavior:
  - comment face is deactivated :cry: 

Proper behavior:
  - comment face stays on :tada:

**Comment by flexibeast** [comment]
i believe i've now fixed this; can you please check?

**Comment by gcentauri** [comment]
Seems to be working!  Funny I noticed that missing `t` late last night and thought i had it working too, but i think i had two different versions mixed up and was very tired :)  Thanks for the fix!

**Comment by flexibeast** [comment]
Great! You're welcome - thanks for the MRE. :-)
