### ISSUE TITLE
Feature: add syntax highlighting to @ variables

### ISSUE THREAD

**Issue by gcentauri** [flexibeast/picolisp-mode#11]
Could be nice to highlight the special @ variables, especially the ones that appear as replacements in strings/transient variables.

**Comment by flexibeast** [comment]
i've now added a new face, `picolisp-at-mark-face`, which inherits from `font-lock-variable-name-face`; it seemed the most appropriate font-lock face to inherit from.

**Comment by gcentauri** [comment]
Makes sense. It works for me, I've been trying to look around at other languages to see if there are any conventions or other highlighting styles for string replacement variables.  I can't seem to find any examples.  Common Lisp format string variables don't have any special highlighting.

Seems like this is fine for now, I'll have to get some more time to spend in PicoLisp and see how the highlighting feels :)

**Comment by flexibeast** [comment]
Great, thanks. :-) Closing.
