### ISSUE TITLE
package errors on load if slime isn't installed

### ISSUE THREAD

**Issue by gcentauri** [flexibeast/picolisp-mode#5]
The current default `picolisp-disable-slime-p` calls `slime-mode` directly.  I don't have `slime` installed so this causes a void symbol error.

I'm working on a potential fix and will push up a PR, but you might have a better way :)

Thanks for the mode by the way!

**Comment by gcentauri** [comment]
PR #4 addresses this issue

**Comment by flexibeast** [comment]
i've just merged PR #4. Sorry it's taken me so long to get to this.
