### ISSUE TITLE
`backward-word` and `forward-word` don't work as expected

### ISSUE THREAD

**Issue by gcentauri** [flexibeast/picolisp-mode#9]
It seems to jump from number to number, which might have something to do with how the syntax-table is defined?

Antergos Linux
Emacs 26.1
MELPA package

**Comment by flexibeast** [comment]
i believe this is now fixed. Could you please test and confirm?

**Comment by gcentauri** [comment]
I will get to it as soon as I can :) Thank you!

**Comment by gcentauri** [comment]
Appears to be working as expected!  I will go ahead and close the issue.
